language: dart
sudo: false
dart:
- stable
- dev

cache:
  directories:
  - $HOME/.pub-cache
  - .dart_tool/build

stages:
- name: analyze
- name: test

jobs:
  include:
  - stage: analyze
    script:
    - dartanalyzer --fatal-warnings .
  - stage: test
    script:
    - pub run test_coverage
    after_success:
    - bash <(curl -s https://codecov.io/bash)
