analyzer:
  strong-mode:
    implicit-casts: false
    implicit-dynamic: true # https://github.com/dart-lang/sdk/issues/25551
  exclude:
  - "**/*.g.dart"

include: package:pedantic/analysis_options.yaml
