name: bitbucket_code_coverage
version: 0.0.1
description: >
  Converts coverage data from LCOV and publishes to Bitbucket server via
  Bitbucket Server Code Coverage plugin API.
authors:
- Artur Stepniewski <artur.stepniewski+github@gmail.com>
homepage: https://github.com/arturdm/bitbucket_code_coverage

environment:
  sdk: ">=2.0.0 <3.0.0"

executables:
  bitbucket_code_coverage:

dependencies:
  args: ^1.4.0
  collection: ^1.14.0
  glob: ^1.1.0
  http: ^0.12.0
  json_annotation: ^2.0.0
  lcov: ^4.1.0
  logging: ^0.11.0
  meta: ^1.1.0
  path: ^1.6.0
  quiver: ^2.0.0

dev_dependencies:
  build_runner: ^1.0.0
  json_serializable: ^2.0.2
  mock_web_server: ^4.0.0
  pedantic: ^1.4.0
  test: ^1.5.3
  test_coverage: ^0.2.3
  test_descriptor: ^1.0.0
