name: bitbucket_code_coverage
version: 0.0.1
homepage: https://github.com/arturdm/bitbucket_code_coverage
author: Artur Stepniewski <artur.stepniewski+github@gmail.com>

environment:
  sdk: ">=2.0.0 <3.0.0"

executables:
  bitbucket_code_coverage:

dependencies:
  args: ^1.4.1
  collection: ^1.14.11
  glob: ^1.1.7
  json_annotation: &json_version ^2.0.0
  lcov: ^4.1.0
  logging: ^0.11.3+2
  path: ^1.6.2

dev_dependencies:
  build_runner: ^1.0.0
  json_serializable: *json_version
  mock_web_server: ^4.0.0
  test: ^1.5.3
  test_coverage: ^0.2.3
  test_descriptor: ^1.0.0

